  # Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 10

#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 20

[[main]]
  name = "Recent Publications"
  url = "#publications"
  weight = 30

[[main]]
  name = "Working Papers"
  url = "#workingpapers"
  weight = 40

[[main]]
  name = "Data"
  url = "#data"
  weight = 50


[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/NCBormann-CV-190817.pdf"
#    weight = 70
